import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Title = styled.h1`
  color: blue;
  &:hover {
    color: red;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Title>akakaka</Title>
    </>
  );
}
